name: Build and deploy to Firebase

on: 
  push: 
    branches: 
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        run: |
          npm install
          npm run functions-ci
          npm install create-elm-app
          npx elm-app build
     
      - name: Publish function
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only "functions:proxy"
        env:
          FIREBASE_TOKEN: ${{secrets.firebase_token}}
          PROJECT_ID: eidjord

      - name: Publish web
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only "hosting:fintstatus"
        env:
          FIREBASE_TOKEN: ${{secrets.firebase_token}}
          PROJECT_ID: eidjord